// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE

  QUESTIONS_REQUEST
  QUESTIONS_RECEIVE
  QUESTIONS_FAILURE

  UPDATE_INTERVIEW_DATA
  UPDATE_INTERVIEW_NAME
  UPDATE_TIME_CONTROL

  START_INTERVIEWEE_TIME
  START_INTERVIEWER_TIME

  STOP_TIMER

  INCREMENT_INTERVIEWEE_TIME
  INCREMENT_INTERVIEWER_TIME

  RESET
`)
